apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 823151423293.dkr.ecr.ap-south-1.amazonaws.com/result:latest
        name: result
        ports:
        - containerPort: 80
          name: result
