apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  ports:
    - port: 80       # Port exposed outside
      targetPort: 80 # Container port
  selector:
    app: result
